# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PRamoneda
email: pramonedaf@gmail.com
description: The personal website of Pedro Ramoneda, researcher, technologist and musician

keywords: computational musicology, Music Information Retrieval

#baseurl: "https://pramoneda.github.io"
#url: "https://pramoneda.github.io"

github_username:  PRamoneda
google_analytics_tracking_id: UA-129738661-1
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
incremental: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ['.htaccess']

papers:
  - authors: "P. Ramoneda, J. J. Valero-Mas, D. Jeong and X. Serra"
    year: "2023"
    title: "Predicting performance difficulty from piano sheet music images"
    link: "https://doi.org/10.1016/j.eswa.2023.121776"
    publication: "In Proc. of the 24th Int. Society for Music Information Retrieval Conf., Milan, Italy."
    tags:
      - name: "Code"
        link: "https://github.com/PRamoneda/pdf-difficulty"
      - name: "Paper"
        link: "https://arxiv.org/pdf/2309.16287.pdf"
      - name: "Dataset"
        link: "https://zenodo.com/record/8126801"
      - name: "Demo"
        link: "https://musiccritic.upf.edu/pdf_difficulty/"
  - authors: "Ramoneda, P., Jeong, D., Eremenko, V., Tamer, N. C., Miron, M. and Serra, X. "
    year: "2024"
    title: "Combining piano performance dimensions for score difficulty classification"
    link: "https://doi.org/10.1016/j.eswa.2023.121776"
    publication: "Expert Systems with Applications, 238"
    tags:
      - name: "Code"
        link: "https://github.com/PRamoneda/difficulty-prediction-CIPI"
      - name: "Paper"
        link: "https://doi.org/10.1016/j.eswa.2023.121776"
      - name: "Dataset"
        link: "https://zenodo.org/records/8037327"
      - name: "Demo"
        link: "https://musiccritic.upf.edu/eswa_difficulty/"
  - authors: "N. C. Tamer, P. Ramoneda, and X. Serra"
    year: "2022"
    title: "Violin Etudes: A comprehensive Dataset for f0 Estimation and Performance Analysis "
    link: "https://repositori.upf.edu/bitstream/handle/10230/54154/Tamer_ismir_viol.pdf?sequence=1&isAllowed=y"
    publication: "In Proc. of the 23rd Int. Society for Music Information Retrieval Conf. (ISMIR)"
    tags:
      - name: "Code"
        link: "https://github.com/PRamoneda/Automatic-Piano-Fingering"
      - name: "Paper"
        link: "https://repositori.upf.edu/bitstream/handle/10230/54154/Tamer_ismir_viol.pdf?sequence=1&isAllowed=y"
      - name: "Dataset"
        link: "https://doi.org/10.5281/zenodo.6564408"
      - name: "Teaser"
        link: "https://youtu.be/qbS9Y4ZgVRM?si=MEmkTd9fHB22AkgN"
  - authors: "Pedro Ramoneda, Dasaem Jeong, Eita Nakamura, Xavier Serra, and Marius Miron"
    year: "2022"
    title: "Automatic Piano Fingering from Partially Annotated Scores using Autoregressive Neural Networks"
    link: "https://ieeexplore.ieee.org/document/9747223/"
    publication: "In Proceedings of the 30th ACM International Conference on Multimedia (MM ’22), October 10–14, 2022, Lisboa, Portugal."
    tags:
      - name: "Code"
        link: "https://github.com/PRamoneda/Automatic-Piano-Fingering"
      - name: "Paper"
        link: "https://repositori.upf.edu/bitstream/handle/10230/54308/Ramoneda_acm_auto.pdf?sequence=1&isAllowed=y"
      - name: "Dataset"
        link: "https://zenodo.org/records/6433702"
      - name: "Demo"
        link: "https://musiccritic.upf.edu/apf_acm"
      - name: "Teaser"
        link: "https://youtu.be/WVLMy2Sf_e0?si=sjPtoyXGwI8KhGf1"
  - authors: "Ramoneda, P., Tamer, N. C., Eremenko, V., Miron, M. & Serra, X"
    year: "2022"
    title: "Score difficulty analysis for piano performance education based on fingering"
    link: "https://ieeexplore.ieee.org/document/9747223/"
    publication: "In ICASSP 2022 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)"
    tags:
      - name: "BibTeX"
        link: "https://pramoneda.github.io/bib/ICASSP22.txt"
      - name: "Arxiv"
        link: "https://arxiv.org/abs/2203.13010"
      - name: "Code"
        link: "https://github.com/PRamoneda/ICASSP22"
      - name: "Dataset"
        link: "https://github.com/PRamoneda/Mikrokosmos-difficulty"
      - name: "Demo"
        link: "https://musiccritic.upf.edu/mikrokosmos/"
      - name: "Teaser"
        link: "https://www.youtube.com/watch?v=vFuOlClISxs"
  - authors: "Kim, H., Ramoneda, P., V., Miron, M. & Serra, X"
    year: "2022"
    title: "An overview of automatic piano performance assessment within the music education context"
    link: "https://doi.org/10.5220/0011137600003182"
    publication: "In Proceedings of the 14th International Conference on Computer Supported Education (CSEDU)"
    tags:
      - name: "BibTeX"
        link: "https://pramoneda.github.io/bib/CSEDU22.txt"
      - name: "PDF"
        link: "https://doi.org/10.5220/0011137600003182"
  - authors: "Bernardes, G., Ramoneda, P. and Miron, M"
    year: "2021"
    title: "Unveiling High-level Discriminant Harmonic Descriptors of Musical Style in the Tonal Interval Space"
    link: "https://www.aes.org/e-lib/browse.cfm?elib=20945"
    publication: "In International Conference on Music Perception and Cognition (ICMPC16-ESCOM11)"
    tags:
      - name: "BibTeX"
        link: "https://pramoneda.github.io/bib/ICMPC21.txt"
      - name: "Pre-print"
        link: "https://www.researchgate.net/publication/350529696_Unveiling_High-level_Discriminant_Harmonic_Descriptors_of_Musical_Style_in_the_Tonal_Interval_Space"
      - name: "Supplementary Material"
        link: "pramoneda.github.io/crossTIV"
  - authors: "Ramoneda, P., Miron, M and Serra, X"
    year: "2021"
    title: "Piano Fingering with Reinforcement Learning"
    link: "https://arxiv.org/abs/2111.08009"
    publication: "In CoRR"
    tags:
      - name: "BibTeX"
        link: "https://pramoneda.github.io/bib/arxiv21.txt"
      - name: "Pre-print"
        link: "https://arxiv.org/abs/2111.08009"
      - name: "Code"
        link: "https://github.com/PRamoneda/RL_PianoFingering"
  - authors: "Ramoneda, P. and Bernardes, G."
    year: "2020"
    title: "Revisiting Hamonic Change Detection"
    link: "https://www.aes.org/e-lib/browse.cfm?elib=20945"
    publication: "In 149th AES convention, the Audio Engineering Society"
    tags:
      - name: "BibTeX"
        link: "https://pramoneda.github.io/bib/AES2020.txt"
      - name: "Pre-print"
        link: "https://www.researchgate.net/publication/342563614_Revisiting_Harmonic_Change_Detection"
      - name: "Code"
        link: "https://github.com/PRamoneda/HCDF"

